# Generated by Django 4.0.3 on 2022-04-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_main_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='content',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
