# Generated by Django 4.0.3 on 2022-04-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_main_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='image1',
            field=models.ImageField(null=True, upload_to='main/'),
        ),
    ]
