# Generated by Django 4.0.3 on 2022-04-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_main_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='image1',
        ),
    ]
