# Generated by Django 4.0.3 on 2022-04-05 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='main/')),
                ('profile_image', models.ImageField(upload_to='profile/')),
                ('content', models.TextField(null=True)),
                ('like_count', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
