# Generated by Django 4.0.3 on 2022-04-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0002_remove_feed_content_remove_feed_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='main',
        ),
    ]
